### GENERATED BY: /home/wb/make-template/autogen.sh @ Mon Oct  5 09:22:54 AM CDT 2026
SHELL := /bin/bash

blue := \033[0;34m
red := \033[0;31m
reset := \033[0m

info := $(blue)[MAKE]$(reset)

## default: list available targets with descriptions
help:
	@grep -E '^## |^[a-zA-Z_-]+:' $(MAKEFILE_LIST) | \
	awk 'BEGIN {FS=":"; bn=0} \
	function flush(    i,sym) { \
		for (i=0; i<bn; i++) { \
			sym = (i==bn-1) ? "└── " : "├── "; \
			printf "%s$(blue)%-16s$(reset) %s\n", sym, bt[i], bd[i]; \
		} \
		bn=0 \
	} \
	/^## / {desc=substr($$0,4)} \
	/^[a-zA-Z_-]+:/ { \
		target=$$1; \
		if (desc) { \
			split(target, parts, "-"); \
			prefix=parts[1]; \
			if (target !~ "-") { \
				flush(); \
				printf "$(blue)%-20s$(reset) %s\n", target, desc; \
				seen[target]=1; \
			} else if (prefix in seen) { \
				bt[bn]=target; bd[bn]=desc; bn++; \
			} else { \
				flush(); \
				printf "$(blue)%-20s$(reset) %s\n", target, desc; \
			} \
		} \
		desc="" \
	} \
	END {flush()}'

### EDIT below

.PHONY: help bootstrap pandoc clean distclean run test test-release install document \
        check build build-readme build-vignettes docs release urlcheck data \
        solar-reference renv-status renv-snapshot flow
.DEFAULT_GOAL := help

TGT := solareclipser
VER := $(shell sed -n 's/^Version: *//p' DESCRIPTION)

# R compiles src/ with make; JOBS=1 to compile one file at a time
JOBS ?= $(shell nproc)
RMAKE := MAKEFLAGS=-j$(JOBS)
RE := $(RMAKE) R -e
MAKEFLAGS += --no-print-directory
# check fails on this R CMD check level or worse; release raises it to warning
# (currently fails on Eigen/cdfchi.f warnings, see "Release check" in TODO.md)
CHECK_ERROR_ON ?= error
# release uses warning unless CHECK_ERROR_ON is given: make release CHECK_ERROR_ON=error
RELEASE_ERROR_ON := $(if $(filter command line,$(origin CHECK_ERROR_ON)),$(CHECK_ERROR_ON),warning)
BUILDDIR := release
TARBALL := $(BUILDDIR)/$(TGT)_$(VER).tar.gz

TOOLS := .tools
PANDOC_VER := 3.12
PANDOC_SHA256 := 67d7d011fed8c8543306022b985b9b2499ab9b74818df91d8727c7e9ebc5ba06
PANDOC_TGZ := pandoc-$(PANDOC_VER)-linux-amd64.tar.gz
PANDOC_BIN := $(TOOLS)/pandoc-$(PANDOC_VER)/bin/pandoc

# Render the vignette into doc/ as devtools::build_vignettes() did (deprecated
# in devtools 2.5, and it adds /doc/ to .gitignore)
VIGNETTE_R := pkgload::load_all(); \
  rmarkdown::render("vignettes/minimal.Rmd", output_dir = "doc"); \
  knitr::purl("vignettes/minimal.Rmd", output = "doc/minimal.R"); \
  invisible(file.copy("vignettes/minimal.Rmd", "doc", overwrite = TRUE))

## Restore pinned R dev dependencies (renv.lock) and pandoc into the project
bootstrap: pandoc
	@printf "$(info):bootstrap\n"
	$(RE) 'renv::restore(prompt = FALSE)'

## Download pinned pandoc into .tools/ and link .tools/pandoc to it (.Rprofile uses that)
pandoc: $(PANDOC_BIN)
	@ln -sfn pandoc-$(PANDOC_VER) $(TOOLS)/pandoc

$(PANDOC_BIN):
	@printf "$(info):pandoc\n"
	mkdir -p $(TOOLS)
	curl -fsSL -o $(TOOLS)/$(PANDOC_TGZ) \
		https://github.com/jgm/pandoc/releases/download/$(PANDOC_VER)/$(PANDOC_TGZ)
	echo "$(PANDOC_SHA256)  $(TOOLS)/$(PANDOC_TGZ)" | sha256sum -c -
	tar -xzf $(TOOLS)/$(PANDOC_TGZ) -C $(TOOLS)
	rm $(TOOLS)/$(PANDOC_TGZ)

## Remove compiled objects in src/
clean:
	@printf "$(info):clean\n"
	rm -f src/*.o src/*.so

## Also remove the check dir and Meta/ (left by devtools::build_vignettes)
distclean: clean
	@printf "$(info):distclean\n"
	rm -rf $(TGT).Rcheck Meta

## Compile src/ and load the package (devtools::load_all)
run:
	@printf "$(info):run\n"
	$(RE) 'devtools::load_all()'

## Run tests (FILTER=fphi to run only test-fphi.R)
test:
	@printf "$(info):test\n"
	$(RE) 'devtools::test($(if $(FILTER),filter = "$(FILTER)", )stop_on_failure = TRUE)'

# test-release: the tarball to test, or download it from GitHub at REF instead
TEST_RELEASE_SRC = $(if $(REF),-v $(VER) -r $(REF),-t $(CURDIR)/$(TARBALL))
TEST_RELEASE := $(CURDIR)/dev/test-release.sh
# --containall gives the container a 64M tmpfs /tmp; --workdir puts it on the host
SIF_EXEC = singularity exec --cleanenv --no-eval --containall --no-home \
	--workdir "$$work" --bind $(CURDIR):$(CURDIR):ro $(SIF)

## Test release/<pkg>_<ver>.tar.gz as is in a fresh R library (SIF=R.sif: in that container, CHECK=1: add R CMD check, REF=main: download from GitHub, ARGS: see dev/test-release.sh -h)
test-release:
	@printf "$(info):test-release\n"
	$(if $(SIF),work=$$(mktemp -d) && \
		$(if $(findstring -k,$(ARGS)),echo "container /tmp is $$work/tmp",trap 'rm -rf "$$work"' EXIT) && \
		$(SIF_EXEC) bash) \
		$(TEST_RELEASE) $(TEST_RELEASE_SRC) $(if $(CHECK),-c) $(ARGS)

## Build and install the package tarball into the renv project library
install: build
	@printf "$(info):install\n"
	$(RMAKE) R CMD INSTALL $(TARBALL)

## Regenerate RcppExports, NAMESPACE and man/ from roxygen comments
document:
	@printf "$(info):document\n"
	$(RE) 'devtools::document()'

## Document, build and check the package (CHECK_ERROR_ON=warning to fail on warnings)
check: pandoc
	@printf "$(info):check\n"
	$(RE) 'devtools::check(error_on = "$(CHECK_ERROR_ON)")'

## Document, then build the package tarball into release/
build: pandoc document
	@printf "$(info):build\n"
	$(RE) 'devtools::build(path = "$(BUILDDIR)/")'

## Render README.Rmd into README.md
build-readme: pandoc
	@printf "$(info):build-readme\n"
	$(RE) 'devtools::build_readme()'

## Build vignettes into doc/
build-vignettes: pandoc
	@printf "$(info):build-vignettes\n"
	$(RE) '$(VIGNETTE_R)'

## Regenerate roxygen docs, README.md and vignettes (doc/)
docs:
	@printf "$(info):docs\n"
	$(MAKE) document
	$(MAKE) build-readme
	$(MAKE) build-vignettes

## Docs, URL check, check (failing on warnings; CHECK_ERROR_ON=error to relax), then tarball into release/
release:
	@printf "$(info):release\n"
	$(MAKE) docs
	$(MAKE) urlcheck
	$(MAKE) check CHECK_ERROR_ON=$(RELEASE_ERROR_ON)
	$(MAKE) build

## Check URLs in DESCRIPTION, docs and README
urlcheck:
	@printf "$(info):urlcheck\n"
	$(RE) 'urlchecker::url_check()'

## Rebuild data/*.rda from data-raw/*.csv
data:
	@printf "$(info):data\n"
	Rscript data-raw/DATASET.R

## Regenerate the original-SOLAR test fixtures (needs tests/solarcli/)
solar-reference:
	@printf "$(info):solar-reference\n"
	dev/solar-reference.sh

## Show differences between renv.lock and the project library
renv-status:
	$(RE) 'renv::status()'

## Record the project library in renv.lock
renv-snapshot:
	$(RE) 'renv::snapshot(prompt = FALSE)'

## Print the dev flow notes
flow:
	@cat dev/doc/flow.md

