### GENERATED BY: /home/wb/make-template/autogen.sh @ Mon Oct  5 09:22:54 AM CDT 2026
SHELL := /bin/bash

blue := \033[0;34m
red := \033[0;31m
reset := \033[0m

info := $(blue)[MAKE]$(reset)

## default: list available targets with descriptions
help:
	@grep -E '^## |^[a-zA-Z_-]+:' $(MAKEFILE_LIST) | \
	awk 'BEGIN {FS=":"; bn=0} \
	function flush(    i,sym) { \
		for (i=0; i<bn; i++) { \
			sym = (i==bn-1) ? "└── " : "├── "; \
			printf "%s$(blue)%-16s$(reset) %s\n", sym, bt[i], bd[i]; \
		} \
		bn=0 \
	} \
	/^## / {desc=substr($$0,4)} \
	/^[a-zA-Z_-]+:/ { \
		target=$$1; \
		if (desc) { \
			split(target, parts, "-"); \
			prefix=parts[1]; \
			if (target !~ "-") { \
				flush(); \
				printf "$(blue)%-20s$(reset) %s\n", target, desc; \
				seen[target]=1; \
			} else if (prefix in seen) { \
				bt[bn]=target; bd[bn]=desc; bn++; \
			} else { \
				flush(); \
				printf "$(blue)%-20s$(reset) %s\n", target, desc; \
			} \
		} \
		desc="" \
	} \
	END {flush()}'

### EDIT below -- generic/language-agnostic starting point. Fill in the
### recipe bodies for whatever this project actually builds/runs/tests
### with (shell script, python venv, node, a compiled toolchain, ...);
### delete any target that doesn't apply.

.PHONY: all bootstrap clean distclean rebuild run test install help \
        document check check-cran build build-readme build-vignettes \
        flow bear push-vm pull-vm
.DEFAULT_GOAL := help

TGT := solareclipser
VER := $(shell sed -n 's/^Version: *//p' DESCRIPTION)
SOPTS ?= 

RE := R -e
BUILDDIR := release
TARBALL := $(BUILDDIR)/$(TGT)_$(VER).tar.gz

VM_USER := wb
#VM_IP := 192.168.4.190
VM_IP := 10.7.230.208

## Regenerate docs and build the package tarball into release/
all: document build

## Install R dev dependencies (devtools, Rcpp, testthat, knitr, rmarkdown)
bootstrap:
	@printf "$(info):bootstrap\n"
	$(RE) 'install.packages(c("devtools", "Rcpp", "testthat", "knitr", "rmarkdown"), repos = "https://cloud.r-project.org")'

## Remove compiled objects in src/
clean:
	@printf "$(info):clean\n"
	rm -f src/*.o src/*.so

## Also remove release/, check dir, and built vignettes (doc/, Meta/)
distclean: clean
	@printf "$(info):distclean\n"
	rm -rf $(BUILDDIR) $(TGT).Rcheck doc Meta

## Clean and rebuild
rebuild: clean all

## Compile and load into an R session (devtools::load_all)
run:
	@printf "$(info):run\n"
	$(RE) 'devtools::load_all()'

## Run tests (FILTER=fphi to run only test-fphi.R)
test:
	@printf "$(info):test\n"
	$(RE) 'devtools::test($(if $(FILTER),filter = "$(FILTER)"))'

## Build and install the package tarball
install: build
	@printf "$(info):install\n"
	R CMD INSTALL $(TARBALL)

## Regenerate RcppExports, NAMESPACE and man/ from roxygen comments
document:
	@printf "$(info):document\n"
	$(RE) 'devtools::document()'

## Build and check the package locally
check:
	@printf "$(info):check\n"
	$(RE) 'devtools::check(error_on = "error")'

## Build and check the package as CRAN would
check-cran:
	@printf "$(info):check-cran\n"
	$(RE) 'devtools::check(error_on = "error", cran = TRUE)'

## Build the package tarball into release/
build:
	@printf "$(info):build\n"
	$(RE) 'devtools::build(path = "$(BUILDDIR)/")'

## Render README.Rmd into README.md
build-readme:
	@printf "$(info):build-readme\n"
	$(RE) 'devtools::build_readme()'

## Build vignettes into doc/
build-vignettes:
	@printf "$(info):build-vignettes\n"
	$(RE) 'devtools::build_vignettes()'

## Print the dev flow notes
flow:
	@cat dev/doc/flow.md

## Regenerate compile_commands.json for clangd
bear:
	@printf "$(info):bear\n"
	bear -- R CMD INSTALL . --preclean
	$(MAKE) run

## rsync this project to the dev VM
push-vm:
	rsync -avz --delete ../$(TGT)/ $(VM_USER)@$(VM_IP):~/$(TGT)/

## rsync this project back from the dev VM
pull-vm:
	rsync -avz --delete $(VM_USER)@$(VM_IP):~/$(TGT)/ ../$(TGT)/
