// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// solar_load_pedigree
int solar_load_pedigree(std::string pedigree_filename, double threshold, std::string output_dir);
RcppExport SEXP _solareclipser_solar_load_pedigree(SEXP pedigree_filenameSEXP, SEXP thresholdSEXP, SEXP output_dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type pedigree_filename(pedigree_filenameSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_dir(output_dirSEXP);
    rcpp_result_gen = Rcpp::wrap(solar_load_pedigree(pedigree_filename, threshold, output_dir));
    return rcpp_result_gen;
END_RCPP
}
// solar_load_phenotype
int solar_load_phenotype(std::string phenotype_filename);
RcppExport SEXP _solareclipser_solar_load_phenotype(SEXP phenotype_filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type phenotype_filename(phenotype_filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(solar_load_phenotype(phenotype_filename));
    return rcpp_result_gen;
END_RCPP
}
// solar_select_trait
int solar_select_trait(std::string trait_name);
RcppExport SEXP _solareclipser_solar_select_trait(SEXP trait_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type trait_name(trait_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(solar_select_trait(trait_name));
    return rcpp_result_gen;
END_RCPP
}
// solar_run_fphi
int solar_run_fphi(std::string output_basename);
RcppExport SEXP _solareclipser_solar_run_fphi(SEXP output_basenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type output_basename(output_basenameSEXP);
    rcpp_result_gen = Rcpp::wrap(solar_run_fphi(output_basename));
    return rcpp_result_gen;
END_RCPP
}
// solar_reset
void solar_reset();
RcppExport SEXP _solareclipser_solar_reset() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    solar_reset();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_solareclipser_solar_load_pedigree", (DL_FUNC) &_solareclipser_solar_load_pedigree, 3},
    {"_solareclipser_solar_load_phenotype", (DL_FUNC) &_solareclipser_solar_load_phenotype, 1},
    {"_solareclipser_solar_select_trait", (DL_FUNC) &_solareclipser_solar_select_trait, 1},
    {"_solareclipser_solar_run_fphi", (DL_FUNC) &_solareclipser_solar_run_fphi, 1},
    {"_solareclipser_solar_reset", (DL_FUNC) &_solareclipser_solar_reset, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_solareclipser(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
