# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Load pedigree file
#'
#' Load a pedigree file for analysis. This must be called before loading phenotypes.
#'
#' @param pedigree_filename Path to the pedigree CSV file
#' @param threshold Kinship threshold (0.0 for theoretical pedigrees, >0 for empirical)
#' @param output_dir Directory where pedigree output files will be created
#' @return `TRUE`, invisibly. Signals an error on failure.
#' @export
solar_load_pedigree <- function(pedigree_filename, threshold = 0.0, output_dir = "") {
    invisible(.Call(`_solareclipser_solar_load_pedigree`, pedigree_filename, threshold, output_dir))
}

#' Load phenotype file
#'
#' Load a phenotype file for analysis. Pedigree must be loaded first.
#'
#' @param phenotype_filename Path to the phenotype CSV file
#' @return `TRUE`, invisibly. Signals an error on failure.
#' @export
solar_load_phenotype <- function(phenotype_filename) {
    invisible(.Call(`_solareclipser_solar_load_phenotype`, phenotype_filename))
}

#' Select trait for analysis
#'
#' Select a trait from the loaded phenotype file. Phenotypes must be loaded first.
#'
#' @param trait_name Name of the trait column in the phenotype file
#' @return `TRUE`, invisibly. Signals an error on failure.
#' @export
solar_select_trait <- function(trait_name) {
    invisible(.Call(`_solareclipser_solar_select_trait`, trait_name))
}

#' Select covariates
#'
#' Set the covariates FPHI adjusts the trait for, replacing any selected
#' before. Uses the syntax of SOLAR's `covariate` command; each element may
#' hold several covariates separated by spaces:
#'   - `"age"`: a phenotype column
#'   - `"age^2"`: a power
#'   - `"age*sex"`: an interaction (any number of variables)
#'   - `"age^1,2"`: shorthand for `"age"`, `"age^2"` (up to `^1,2,3,4`)
#'   - `"age#sex"`: shorthand for `"age"`, `"sex"`, `"age*sex"`; combined
#'     with the above, `"age^1,2#sex"` also adds `"age^2"`, `"age^2*sex"`
#'
#' As in SOLAR's `fphi`, each variable is centred on its mean over the
#' individuals analysed, except `sex`, which is recoded so that 2 (or `F`)
#' is 1 and anything else 0. Individuals missing any covariate variable
#' are left out of the analysis. Variable names match phenotype columns
#' ignoring case. Covariates are kept until changed, [solar_reset()], or
#' a call with no covariates.
#'
#' @param covariates Character vector of covariate specs (default: none,
#'   which clears the covariates)
#' @return The expanded covariate names, invisibly, in the order their
#'   betas are reported. Signals an error if a spec is invalid or, when
#'   phenotypes are loaded, names a column that is not in the file.
#' @export
solar_select_covariates <- function(covariates = as.character( c())) {
    invisible(.Call(`_solareclipser_solar_select_covariates`, covariates))
}

#' Run FPHI analysis
#'
#' Run FPHI heritability analysis for the selected trait, adjusted for any
#' covariates set with [solar_select_covariates()].
#' Pedigree, phenotypes, and trait must all be loaded/selected first.
#'
#' By default nothing is printed and only the EVD working files
#' `<output_basename>.ids`, `.eigenvalues`, `.eigenvectors` and `.notes` are
#' created. To also get the results as text, list formats in `format`: each
#' is printed to standard output, in the order given, and when `write_files`
#' is `TRUE` written to its result file(s):
#'   - `"csv"`, `"tsv"`: a results table and a parameters table
#'     (read with [utils::read.csv()] / [utils::read.delim()]);
#'     `<output_basename>_fphi_results.out` and `_parameters.out` (csv),
#'     `_fphi_results.tsv` and `_parameters.tsv` (tsv)
#'   - `"json"`, `"yaml"`: one document holding results and parameters;
#'     `<output_basename>_fphi.json`, `_fphi.yaml`
#'   - `"solar"`: the summary block printed by the original SOLAR-Eclipse
#'     `fphi` command, for diffing against its output;
#'     `<output_basename>_fphi.solar.out`
#'
#' @param output_basename Base name for output files (default: "fphi_output")
#' @param format Character vector of text formats to print: any of "csv",
#'   "tsv", "json", "yaml", "solar" (default: none)
#' @param write_files Write the result files of the formats in `format`
#'   (default: TRUE)
#' @return A list of two data frames:
#'   - `results`: one row with `trait`, `h2r`, `se` (of h2r), `loglik`,
#'     `sporadic_loglik`, `p_value` and `n_subjects`
#'   - `parameters`: one row per fitted parameter, with columns
#'     `parameter`, `value` and `se`: the beta of each covariate (named as
#'     returned by [solar_select_covariates()]), then `mean`, `e2`, `h2r`
#'     and `sd`
#'
#'   The pedigree and phenotype file names are kept in the list's
#'   `pedigree` and `phenotypes` attributes. Signals an error on failure.
#' @export
solar_run_fphi <- function(output_basename = "fphi_output", format = as.character( c()), write_files = TRUE) {
    .Call(`_solareclipser_solar_run_fphi`, output_basename, format, write_files)
}

#' Reset session state
#'
#' Clear all loaded data (pedigree, phenotypes, selected trait, covariates).
#' Useful for starting a new analysis or freeing memory.
#'
#' @export
solar_reset <- function() {
    invisible(.Call(`_solareclipser_solar_reset`))
}

