# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Load pedigree file
#'
#' Load a pedigree file for analysis. This must be called before loading phenotypes.
#'
#' @param pedigree_filename Path to the pedigree CSV file
#' @param threshold Kinship threshold (0.0 for theoretical pedigrees, >0 for empirical)
#' @param output_dir Directory where pedigree output files will be created
#' @return Returns 0 on success, 1 on failure
#' @export
solar_load_pedigree <- function(pedigree_filename, threshold = 0.0, output_dir = "") {
    .Call(`_solareclipser_solar_load_pedigree`, pedigree_filename, threshold, output_dir)
}

#' Load phenotype file
#'
#' Load a phenotype file for analysis. Pedigree must be loaded first.
#'
#' @param phenotype_filename Path to the phenotype CSV file
#' @return Returns 0 on success, 1 on failure
#' @export
solar_load_phenotype <- function(phenotype_filename) {
    .Call(`_solareclipser_solar_load_phenotype`, phenotype_filename)
}

#' Select trait for analysis
#'
#' Select a trait from the loaded phenotype file. Phenotypes must be loaded first.
#'
#' @param trait_name Name of the trait column in the phenotype file
#' @return Returns 0 on success, 1 on failure
#' @export
solar_select_trait <- function(trait_name) {
    .Call(`_solareclipser_solar_select_trait`, trait_name)
}

#' Run FPHI analysis
#'
#' Run FPHI heritability analysis for the selected trait.
#' Pedigree, phenotypes, and trait must all be loaded/selected first.
#'
#' Creates output files:
#'   - <output_basename>.ids
#'   - <output_basename>.eigenvalues
#'   - <output_basename>.eigenvectors
#'   - <output_basename>.notes
#'   - <output_basename>_fphi_results.out
#'   - <output_basename>_parameters.out
#'
#' @param output_basename Base name for output files (default: "fphi_output")
#' @return Returns 0 on success, 1 on failure
#' @export
solar_run_fphi <- function(output_basename = "fphi_output") {
    .Call(`_solareclipser_solar_run_fphi`, output_basename)
}

#' Reset session state
#'
#' Clear all loaded data (pedigree, phenotypes, selected trait).
#' Useful for starting a new analysis or freeing memory.
#'
#' @export
solar_reset <- function() {
    invisible(.Call(`_solareclipser_solar_reset`))
}

