# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Load pedigree file
#'
#' Load a pedigree file for analysis. This must be called before loading phenotypes.
#'
#' @param pedigree_filename Path to the pedigree CSV file
#' @param threshold Kinship threshold (0.0 for theoretical pedigrees, >0 for empirical)
#' @param output_dir Directory where pedigree output files will be created
#' @return Returns 0 on success, 1 on failure
#' @export
solar_load_pedigree <- function(pedigree_filename, threshold = 0.0, output_dir = "") {
    .Call(`_solareclipser_solar_load_pedigree`, pedigree_filename, threshold, output_dir)
}

#' Load phenotype file
#'
#' Load a phenotype file for analysis. Pedigree must be loaded first.
#'
#' @param phenotype_filename Path to the phenotype CSV file
#' @return Returns 0 on success, 1 on failure
#' @export
solar_load_phenotype <- function(phenotype_filename) {
    .Call(`_solareclipser_solar_load_phenotype`, phenotype_filename)
}

#' Select trait for analysis
#'
#' Select a trait from the loaded phenotype file. Phenotypes must be loaded first.
#'
#' @param trait_name Name of the trait column in the phenotype file
#' @return Returns 0 on success, 1 on failure
#' @export
solar_select_trait <- function(trait_name) {
    .Call(`_solareclipser_solar_select_trait`, trait_name)
}

#' Run FPHI analysis
#'
#' Run FPHI heritability analysis for the selected trait.
#' Pedigree, phenotypes, and trait must all be loaded/selected first.
#'
#' The results are printed to standard output in each requested format, in
#' the order given. Progress messages go to standard error, so standard
#' output can be redirected straight to a parsable (or diffable) file.
#'
#' Formats:
#'   - `"csv"`, `"tsv"`: a results table and a parameters table
#'     (read with [utils::read.csv()] / [utils::read.delim()])
#'   - `"json"`, `"yaml"`: one document holding results and parameters
#'   - `"solar"`: the summary block printed by the original SOLAR-Eclipse
#'     `fphi` command, for diffing against its output
#'
#' Always creates the EVD working files `<output_basename>.ids`,
#' `.eigenvalues`, `.eigenvectors` and `.notes`. When `write_files` is
#' `TRUE`, each format also writes its result file(s):
#'   - csv: `<output_basename>_fphi_results.out`, `<output_basename>_parameters.out`
#'   - tsv: `<output_basename>_fphi_results.tsv`, `<output_basename>_parameters.tsv`
#'   - json: `<output_basename>_fphi.json`
#'   - yaml: `<output_basename>_fphi.yaml`
#'   - solar: `<output_basename>_fphi.solar.out`
#'
#' @param output_basename Base name for output files (default: "fphi_output")
#' @param format Character vector of output formats: any of "csv", "tsv",
#'   "json", "yaml", "solar" (default: "csv")
#' @param write_files Write the result files to disk (default: TRUE)
#' @return Returns 0 on success, 1 on failure
#' @export
solar_run_fphi <- function(output_basename = "fphi_output", format = as.character( c("csv")), write_files = TRUE) {
    .Call(`_solareclipser_solar_run_fphi`, output_basename, format, write_files)
}

#' Reset session state
#'
#' Clear all loaded data (pedigree, phenotypes, selected trait).
#' Useful for starting a new analysis or freeing memory.
#'
#' @export
solar_reset <- function() {
    invisible(.Call(`_solareclipser_solar_reset`))
}

